name: Dependabot Auto-Approve

on:
    pull_request_target:
        types: [opened, synchronize, reopened]

permissions:
    pull-requests: write

jobs:
    auto-approve:
        name: Auto-approve Dependabot PRs
        runs-on: ubuntu-latest
        if: github.event.pull_request.user.login == 'dependabot[bot]'

        steps:
            - name: Fetch Dependabot metadata
              id: metadata
              uses: dependabot/fetch-metadata@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Check if PR should be auto-approved
              id: check-approve
              run: |
                  # Default to not approving
                  echo "should_approve=false" >> $GITHUB_OUTPUT

                  UPDATE_TYPE="${{ steps.metadata.outputs.update-type }}"
                  DEPENDENCY_TYPE="${{ steps.metadata.outputs.dependency-type }}"

                  # Auto-approve same conditions as auto-merge
                  if [[ "$UPDATE_TYPE" == "version-update:semver-patch" ]]; then
                    echo "should_approve=true" >> $GITHUB_OUTPUT
                  elif [[ "$UPDATE_TYPE" == "version-update:semver-minor" && "$DEPENDENCY_TYPE" == "development" ]]; then
                    echo "should_approve=true" >> $GITHUB_OUTPUT
                  fi

            - name: Auto-approve PR
              if: steps.check-approve.outputs.should_approve == 'true'
              uses: actions/github-script@v7
              with:
                  script: |
                      const { owner, repo } = context.repo;
                      const pr_number = context.payload.pull_request.number;

                      await github.rest.pulls.createReview({
                        owner,
                        repo,
                        pull_number: pr_number,
                        event: 'APPROVE',
                        body: 'Auto-approved by Dependabot workflow for patch/minor dev dependency update'
                      });

                      console.log(`Approved PR #${pr_number}`);
